gastos/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ListadoProveedores, DetalleProveedor, ModificarProveedor, NuevoProveedor, EliminarProveedor
from .views import ListadoGastos, DetalleGasto, ModificarGasto, NuevoGasto, EliminarGasto

app_name = 'gastos'

urlpatterns = [

    url(r'^listado_proveedores/$', ListadoProveedores.as_view(), name="listado_proveedores"),
    url(r'^detalle_proveedor/(?P<pk>.+)/$', DetalleProveedor.as_view(), name="detalle_proveedor"),
    url(r'^modificar_proveedor/(?P<pk>.+)/$', ModificarProveedor.as_view(), name="modificar_proveedor"),
    url(r'^nuevo_proveedor/', NuevoProveedor.as_view(), name="nuevo_proveedor"),
    url(r'^proveedor/(?P<pk>[0-9]+)/delete/$', EliminarProveedor.as_view(), name="proveedor_eliminar"),

    url(r'^listado_gastos/$', ListadoGastos.as_view(), name="listado_gastos"),
    url(r'^detalle_gasto/(?P<pk>.+)/$', DetalleGasto.as_view(), name="detalle_gasto"),
    url(r'^modificar_gasto/(?P<pk>.+)/$', ModificarGasto.as_view(), name="modificar_gasto"),
    url(r'^nuevo_gasto/', NuevoGasto.as_view(), name="nuevo_gasto"),
    url(r'^gasto/(?P<pk>[0-9]+)/delete/$', EliminarGasto.as_view(), name="gasto_eliminar"),
]

ozonemanagement/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.static import serve
from . import views

urlpatterns = [


url('albaranes/', include('albaranes.urls', namespace='albaranes')),
    url('articulos/', include('articulos.urls', namespace='articulos')),
    url('clientes/', include('clientes.urls', namespace='clientes')),
    url('pedidos/', include('pedidos.urls', namespace='pedidos')),
    url('almacen/', include('almacen.urls', namespace='almacen')),
    url('gastos/', include('gastos.urls', namespace='gastos')),
    url('profesionales/', include('profesionales.urls', namespace='profesionales')),


    path('admin/', admin.site.urls),
    url(r'^login/', auth_views.LoginView.as_view(), {'template_name': 'templates/login.html'}, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), {'template_name': 'templates/logged_out.html'}, name='logout'),
    url(r'^', views.index),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedidos/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ListadoPedidos, NuevoPedido, EliminarPedido,ModificarPedido
from . import views

app_name = 'pedidos'
urlpatterns = [

    url(r'^listado_pedidos/$', ListadoPedidos.as_view(), name="listado_pedidos"),
    url(r'^nuevo_pedido/', NuevoPedido.as_view(), name="nuevo_pedido"),
    url(r'^modificar_pedido/(?P<pk>.+)/$', ModificarPedido.as_view(), name="modificar_pedido"),
    url(r'^pedido/(?P<pk>[0-9]+)/delete/$', EliminarPedido.as_view(), name="pedido_eliminar"),
    url(r'^addarticulo_pedido/(?P<pk>.+)/$', views.AddArticuloPedido, name="addarticulo_pedido"),
    url(r'^detalle_pedido/(?P<pk>.+)/$', views.DetalleArticuloPedido, name="detalle_pedido"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gastos/models.py
import os
from django.db import models
from django_extensions.db.models import TimeStampedModel
from datetime import datetime
import django.utils.timezone
from django import forms


NIF = 1
NIE = 2
CIF = 3

TIPODOCUMENTO = (
    (NIF, 'Nif'),
    (NIE, 'Nie'),
    (CIF, 'Cif'),
)

FACTURA = 1
TICKET = 2

TIPODOCUMENTO_GASTO = (
    (FACTURA, 'Factura'),
    (TICKET, 'Ticket'),
)

TARJETA = 1
TRANSFERENCIA = 2
EFECTIVO = 3
INGRESO = 4

FORMAPAGO = (
    (TARJETA, 'Tarjeta de Credito'),
    (TRANSFERENCIA, 'Transferencia Bancaria'),
    (EFECTIVO, 'Efectivo'),
    (INGRESO, 'Ingreso Bancario'),
)


GENERAL = 1
REDUCIDO = 2
SUPER = 3

IVA = (
    (GENERAL, 'Iva General (21%)'),
    (REDUCIDO, 'Iva Reducido (10%)'),
    (SUPER, 'Iva Superreducido (4%)'),
)


class GrupoGasto(TimeStampedModel):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Grupo de gasto"
        verbose_name_plural = "Grupos de Gastos"
        ordering = ['-created']

class Proveedor(TimeStampedModel):

#DATOS SOBRE PROVEEDORES
    razon_social = models.CharField(max_length=255, null=True)
    tipo_documento = models.IntegerField(default=CIF, choices=TIPODOCUMENTO, db_index=True, null=True)
    num_documento = models.CharField(max_length=30, null=True)
    fecha_alta = models.DateField(default=django.utils.timezone.now, null=True)
    dir_calle = models.CharField(max_length=255, verbose_name="calle", null=True)
    dir_numero = models.CharField(max_length=25, verbose_name="numero" ,null=True, blank=True)
    dir_piso_puerta = models.CharField(max_length=255, verbose_name="piso puerta", null=True, blank=True )
    cod_postal = models.IntegerField(null=True)
    provincias = models.ForeignKey("clientes.Provincias", db_index=True, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Provincia")
    poblacion = models.ForeignKey("clientes.Poblacion", db_index=True, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Población")


    def tipo_documento_display(self):
        return '%s' % (self.get_tipo_documento_display())


    def __str__(self):
        return "{} {}".format(self.razon_social, self.num_documento)



    class Meta:
        verbose_name = "Proveedor"
        verbose_name_plural = "Proveedores"
        ordering = ['-created']

class Gasto(TimeStampedModel):
#DATOS SOBRE GASTOS
    nombre = models.CharField(max_length=255)
    fecha = models.DateField(default=django.utils.timezone.now, editable=True, null=True, blank=True)
    Descripcion = models.CharField(max_length=255, blank=True, null=True)
    num_factura = models.CharField(max_length=255, blank=True, null=True)
    tipo_doc = models.IntegerField(default=TICKET, choices=TIPODOCUMENTO_GASTO, db_index=True, null=True, blank=True)
    proveedor = models.ForeignKey("Proveedor", db_index=True, on_delete=models.CASCADE)
    iva = models.IntegerField(default=GENERAL, choices=IVA, db_index=True, null=True, blank=True)
    forma_pago = models.IntegerField(default=EFECTIVO, choices=FORMAPAGO, db_index=True, null=True, blank=True)
    almacenable = models.BooleanField(default=False)
    unidades = models.PositiveIntegerField(blank=True, null=True)
    fecha_caducidad = models.DateField(default=django.utils.timezone.now, editable=True, null=True, blank=True)
    documento = models.FileField(upload_to='documentos_gastos', null=True, blank=True)

    def tipo_doc_display(self):
        return '%s' % (self.get_tipo_doc_display())


    def forma_pago_display(self):
        return '%s' % (self.get_forma_pago_display())

    def iva_display(self):
        return '%s' % (self.get_iva_display())


    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Gasto"
        verbose_name_plural = "Gastos"
        ordering = ['-created']

gastos/forms.py
from django import forms
from .models import Proveedor, Gasto


class ProveedorForm(forms.ModelForm):

    class Meta:
        model = Proveedor
        fields='__all__'

    def __init__(self, *args, **kwargs):
        super(ProveedorForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):

            self.fields[field].widget.attrs.update({
                'class': 'form-control border-primary'
            })


class GastoForm(forms.ModelForm):

    class Meta:
        model = Gasto
        fields='__all__'

    def __init__(self, *args, **kwargs):
        super(GastoForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):

            self.fields[field].widget.attrs.update({
                'class': 'form-control border-primary'
            })

gastos/views.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from .forms import ProveedorForm , GastoForm
from .models import Proveedor, Gasto



class ListadoProveedores(ListView):
    model = Proveedor
    template_name = 'listado_proveedores.html'
    context_object_name ='proveedores'

class DetalleProveedor(DetailView):
    model = Proveedor
    template_name = 'detalle_proveedor.html'

class ModificarProveedor(UpdateView):
    model = Proveedor
    template_name = 'modificar_proveedor.html'
    form_class = ProveedorForm
    success_url = reverse_lazy('gastos:listado_proveedores')

class NuevoProveedor(CreateView):
    model = Proveedor
    template_name = 'nuevo_proveedor.html'
    form_class = ProveedorForm
    success_url = reverse_lazy('gastos:listado_proveedores')

class EliminarProveedor(DeleteView):
    model = Proveedor
    template_name = 'proveedor_eliminar.html'
    success_url = reverse_lazy('gastos:listado_proveedores')




class ListadoGastos(ListView):
    model = Gasto
    template_name = 'listado_gastos.html'
    context_object_name ='gastos'

class DetalleGasto(DetailView):
    model = Gasto
    template_name = 'detalle_gasto.html'

class ModificarGasto(UpdateView):
    model = Gasto
    template_name = 'modificar_gasto.html'
    form_class = GastoForm
    success_url = reverse_lazy('gastos:listado_gastos')

class NuevoGasto(CreateView):
    model = Gasto
    template_name = 'nuevo_gasto.html'
    form_class = GastoForm
    success_url = reverse_lazy('gastos:listado_gastos')

class EliminarGasto(DeleteView):
    model = Gasto
    template_name = 'gasto_eliminar.html'
    success_url = reverse_lazy('gastos:listado_gastos')

gastos/templates/detalle_gasto.html
{% extends "base.html" %}
{% load staticfiles %}

{% block cuerpo %}
{% with menudetalle="1" pk=gasto.pk %}

{% endwith %}
<div class="row">
			<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card">
              <div class="card">
                  <div class="card-body">
					<h3 class="card-title"></h3>
					<h3 class="card-title"><i class="mdi mdi-account-location text-primary icon-md mr-0 mr-sm-4">
					</i>Información del Gasto</h3>

					<hr>
                        <p>Num Factura:  &nbsp;	    <label>{{ gasto.num_factura | default_if_none:"" }}</label></p>
					    <p>Nombre:		&nbsp;   	<label>{{ gasto.nombre | default_if_none:"" }}</label></p>
                        <p>Fecha :  &nbsp;          <label>{{ gasto.fecha | default_if_none:"" }}</label></p>
                        <p>Fecha Caducidad:   &nbsp;<label>{{ gasto.fecha_caducidad | default_if_none:"" }}</label></p>
                        <p>Descripción:   &nbsp;    <label>{{ gasto.descripcion | default_if_none:"" }}</label></p>
				</div>
			</div>
		</div>

				<!-- card 1-->
		<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card ">
              <div class="card">
                <div class="card-body">

					<h3 class="card-title"></h3>
					<h3 class="card-title"><i class="mdi mdi-more text-primary icon-md mr-0 mr-sm-4">
					</i>Información adicional</h3>
					<hr>


                        <p>Proveedor:         &nbsp;<label>{{ gasto.proveedor | default_if_none:"" }}</label></p>
                        <p>IVA:        &nbsp;       <label>{{ gasto.iva_display | default_if_none:"" }}</label></p>
                        <p>Forma de Pago:     &nbsp;<label>{{ gasto.forma_pago_display | default_if_none:"" }}</label></p>
                        <p>Unidades:          &nbsp;<label>{{ gasto.unidades | default_if_none:"" }}</label></p>

                        <p><label class="form-check-label">Almacenable: &nbsp;</label>
                            {% if gasto.almacenable %}
                                <input class="" style="pointer-events: none;" type="checkbox" checked>
                                {% else %}
                                <input style="pointer-events:none;" type="checkbox" uncheked>
                            {% endif %}
                        </p>
				</div>
			  </div>
        </div>
</div>

		<div class="modal-footer">
			<a role="button" class="btn btn-outline-danger btn-sm" href="{% url 'gastos:listado_gastos' %}">volver</a>
		</div>

{% endblock cuerpo %}

gastos/templates/detalle_proveedor.html
{% extends "base.html" %}
{% load staticfiles %}

{% block cuerpo %}
{% with menudetalle="1" pk=proveedor.pk %}

{% endwith %}
<div class="row">
			<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card">
              <div class="card">
                  <div class="card-body">
					<h3 class="card-title"></h3>
					<h3 class="card-title"><i class="mdi mdi-account-location text-primary icon-md mr-0 mr-sm-4">
					</i>Información del Proveedor</h3>

					<hr>
					<p>Razón Social:  &nbsp;	<label>{{ proveedor.razon_social | default_if_none:"" | truncatechars:25}}</label></p>
					<p>Tipo Documento:   &nbsp; <label>{{ proveedor.tipo_documento_display | default_if_none:"" }}</label></p>
					<p>Número Documento:  &nbsp;<label>{{ proveedor.num_documento | default_if_none:"" }}</label></p>
					<p>Fecha Alta:        &nbsp;<label>{{ proveedor.fecha_alta | default_if_none:"" }}</label></p>

				</div>
			</div>
		</div>

				<!-- card 1-->
		<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card ">
              <div class="card">
                <div class="card-body">

					<h3 class="card-title"></h3>
					<h3 class="card-title"><i class="mdi mdi-more text-primary icon-md mr-0 mr-sm-4">
					</i>Información adicional</h3>
					<hr>

                    <p class="card-description">  </p>

                    <p>Calle:   	      &nbsp;<label>{{ proveedor.dir_calle | default_if_none:"" | truncatechars:25}}</label></p>
					<p>Número:   	      &nbsp;<label>{{ proveedor.dir_numero | default_if_none:"" }}</label></p>
					<p>Piso/Puerta:   	      &nbsp;<label>{{ proveedor.dir_piso_puerta | default_if_none:"" }}</label></p>
					<p>CP:   		&nbsp;	    <label>{{ proveedor.cod_postal | default_if_none:"" }}</label></p>
					<p>Población:         &nbsp;<label>{{ proveedor.poblacion | default_if_none:"" }}</label></p>
					<p>Provincia:         &nbsp;<label>{{ proveedor.provincias | default_if_none:"" }}</label></p>
				</div>
			  </div>
        </div>
</div>

		<div class="modal-footer">
			<a role="button" class="btn btn-outline-danger btn-sm" href="{% url 'gastos:listado_proveedores' %}">volver</a>
		</div>

{% endblock cuerpo %}

gastos/templates/gasto_eliminar.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

  <h5> Eliminando Gasto id:{{ object.pk }}</h5>

            <form method="post" action="{% url 'gastos:gasto_eliminar' object.pk %}">{% csrf_token %}
                <p>Seguro que quieres eliminar este gasto "{{ object }}"?</p>
                <input type="submit" class="btn btn-danger" value="Eliminar">
            </form>


</div>
      <div>
        <button type="button" class="btn btn-secondary justify-content-right" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

{% endblock cuerpo %}

gastos/templates/listado_gastos.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}

      <!-- partial -->

<style>
.dataTables_wrapper .dataTable .btn{
     padding: 0.4rem 0.9rem!important;
    vertical-align: top;
}
</style>


<div class="row">
  <div class="col-md-12">
            <div class="card" >
              <div class="card-body">
                  <h3 class="card-title">Listado de Gastos</h3>
                  <p class="card-description">  </p>
                <div class="row">
                  <div class="col-12 table-responsive">
                    <table id="tabla" class="table">
                      <thead>
                        <tr>

                             <th>Gasto</th>
                             <th>Proveedor </th>
                             <th>Fecha  </th>
                             <th>Número Factura</th>
                             <th> <a role="button" class="btn btn-outline-warning btn-sm" href="{% url 'gastos:nuevo_gasto' %}">Nuevo Gasto</a></th>
                        </tr>
                      </thead>

                      <tbody>

                        {% for 	gas in gastos %}

                            <tr>

                                <td>{{ gas.nombre | default_if_none:"" | truncatechars:25 }}</td>
                                <td>{{ gas.proveedor | default_if_none:"" }} </td>
                                <td>{{ gas.fecha | default_if_none:""  }}</td>
                                <td>{{ gas.num_factura | default_if_none:"" }}</td>
                                <td>
                                    <a role="button" class="btn btn-outline-primary btn-sm" href="{% url 'gastos:detalle_gasto' gas.pk %}">ver</a>
                                    <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'gastos:modificar_gasto' gas.pk %}">editar</a>
                                    <a onclick="return abrir_modal('{% url 'gastos:gasto_eliminar' gas.pk %}')">
                                        <span class="btn btn-outline-danger mdi mdi-delete"></span>
                                    </a>
                                </td>
                            </tr>
			            {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

  </div>
</div>
<div id="popup" class="modal fade" role="dialog">


</div>
{% endblock cuerpo %}

{% block js %}

<script>
function abrir_modal(url)
{
	$('#popup').load(url, function()
	{
		$(this).modal('show');
	});
	return false;
}

function cerrar_modal()
{
	$('#popup').modal('hide');
	return false;
}

$(document).ready(function()
{
    var table = $('#tabla').dataTable( {
        "language": {
        	url: "/static/assets/localizacion/es_ES.json"
        }
    } );
});
</script>


    <!-- Custom js for this page
    <script src="{% static '/assets/js/shared/data-table.js' %}"></script>-->
          <script src="{% static 'assets/js/shared/modal-demo.js' %}"></script>
   <!--<script src="{% static 'assets/js/shared/jquery.dataTables.min.js' %}"></script>-->
   <!-- End custom js for this page-->

{% endblock js %}

gastos/templates/listado_proveedores.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}

{% with menuproveedor="1" pk=proveedor.pk %}
	{% include "menuarticulos.html" %}
{% endwith %}

      <!-- partial -->

<style>
.dataTables_wrapper .dataTable .btn{
     padding: 0.4rem 0.9rem!important;
    vertical-align: top;
}
</style>


<div class="row">
  <div class="col-md-12">
            <div class="card" >
              <div class="card-body">
                  <h3 class="card-title">Listado de Proveedores</h3>
                  <p class="card-description">  </p>
                <div class="row">
                  <div class="col-12 table-responsive">
                    <table id="tabla" class="table">
                      <thead>
                        <tr>
                             <th>Razón Social </th>
                             <th>CIF</th>
                             <th>Fecha Alta</th>
                             <th> <a role="button" class="btn btn-outline-warning btn-sm" href="{% url 'gastos:nuevo_proveedor' %}">Nuevo Proveedor</a></th>
                        </tr>
                      </thead>

                      <tbody>

                        {% for 	prov in proveedores %}

                            <tr>
                                <td>{{ prov.razon_social | default_if_none:"" | truncatechars:25 }}</td>
                                <td>{{ prov.num_documento | default_if_none:"" }}</td>
                                <td>{{ prov.fecha_alta | default_if_none:"" }} </td>
                                <td>
                                    <a role="button" class="btn btn-outline-primary btn-sm" href="{% url 'gastos:detalle_proveedor' prov.pk %}">ver</a>
                                    <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'gastos:modificar_proveedor' prov.pk %}">editar</a>
                                    <a onclick="return abrir_modal('{% url 'gastos:proveedor_eliminar' prov.pk %}')">
                                        <span class="btn btn-outline-danger mdi mdi-delete"></span>
                                    </a>
                                </td>
                            </tr>
			            {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
  </div>
</div>
<div id="popup" class="modal fade" role="dialog">


</div>
{% endblock cuerpo %}

{% block js %}

<script>
function abrir_modal(url)
{
	$('#popup').load(url, function()
	{
		$(this).modal('show');
	});
	return false;
}

function cerrar_modal()
{
	$('#popup').modal('hide');
	return false;
}

$(document).ready(function()
{
    var table = $('#tabla').dataTable( {
        "language": {
        	url: "/static/assets/localizacion/es_ES.json"
        }
    } );
});
</script>


    <!-- Custom js for this page
    <script src="{% static '/assets/js/shared/data-table.js' %}"></script>-->
          <script src="{% static 'assets/js/shared/modal-demo.js' %}"></script>
   <!--<script src="{% static 'assets/js/shared/jquery.dataTables.min.js' %}"></script>-->
   <!-- End custom js for this page-->

{% endblock js %}

gastos/templates/menu_pedidos.html
<nav class="navbar bg-light text-center nav-bottom">

    <div class="container d-flex justify-content-center">

        <ul class="nav nav-tabs tab-solid tab-solid" role="tablist">
                <li class="nav-item"><a class="btn btn-outline-primary" href="{% url 'clientes:listado_pedidos' %}">Pedidos</a> </li>
            <li class="nav-item"><a class="btn btn-outline-primary" href="{% url 'gastos:listado_proveedores' %}">Proveedores</a> </li>
        </ul>
    </div>
</nav>

gastos/templates/modificar_gasto.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}


                    <div class="container">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Modificando Gasto</h3>
                            <p class="card-description">  </p>
                        <form role="form" action="{% url 'gastos:modificar_gasto' object.pk %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label> <p>Gasto</p> {{ form.nombre }}</label>
                                <label> <p>Fecha</p> {{ form.fecha }}</label>
                                <label> <p>Nº Factura</p> {{ form.num_factura }}</label>
                                <label> <p>Descripción</p> {{ form.Descripcion }}</label>
                                        <p>Proveedor {{form.proveedor}}</p>
                                        <p>IVA {{form.iva}}</p>
                                        <p>Forma de Pago {{form.forma_pago}}</p>
                                        <p>Tipo de Pago {{form.tipo_doc}}</p>
                                        <p>Unidades {{form.unidades}}</p>
                                        <p>Fecha Caducidad {{form.fecha_caducidad}}</p>
                                        <p>Almacenable {{form.almacenable}}</p>
                            </div>
                            <div>
                                <div class="col-lg-12 text-right">
                                    <input type="submit" class="btn btn-outline-success" name="submit" value="Guardar">
                                    <a role="button" class="btn btn-outline-danger" href="{{request.META.HTTP_REFERER}}">Cancelar</a>
                                </div>
                            </div>
                        </form>
                      </div>
                    </div>
                    </div>

{% endblock cuerpo %}

gastos/templates/modificar_proveedor.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}


                    <div class="container">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Modificando Proveedor</h3>
                            <p class="card-description">  </p>
                        <form role="form" action="{% url 'gastos:modificar_proveedor' object.pk %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <div>
                                <div class="col-lg-12 text-right">
                                    <input type="submit" class="btn btn-outline-success" name="submit" value="Guardar">
                                    <a role="button" class="btn btn-outline-danger" href="{{request.META.HTTP_REFERER}}">Cancelar</a>
                                </div>
                            </div>
                        </form>
                      </div>
                    </div>
                    </div>

{% endblock cuerpo %}

gastos/templates/nuevo_gasto.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}

<div class="container">
<div class="card">
    <div class="card-body">
		<form class="forms-group" role="form" action="{% url 'gastos:nuevo_gasto' %}" method="post" enctype="multipart/form-data" >
			<h3 class="card-title">Nuevo Gasto</h3>
            <p class="card-description">  </p>

            <div class="body">
				{% csrf_token %}
				<div class="panel panel-default">
					<div class="panel-body">
						{{ form.as_p }}
					</div>
				</div>
			</div>

			<div>
				<div class="col-lg-12 text-right">
					<input type="submit" class="btn btn-primary" name="submit" value="Guardar">
					<a role="button" class="btn btn-outline-danger" href="{{request.META.HTTP_REFERER}}">Cancelar</a>
				</div>
			</div>
		</form>
	</div>
</div>
</div>


{% endblock cuerpo %}

gastos/templates/nuevo_proveedor.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}

<div class="container">
<div class="card">
    <div class="card-body">
		<form class="forms-group" role="form" action="{% url 'gastos:nuevo_proveedor' %}" method="post" enctype="multipart/form-data" >
			<h3 class="card-title">Nuevo Proveedor</h3>
            <p class="card-description">  </p>

            <div class="body">
				{% csrf_token %}
				<div class="panel panel-default">
					<div class="panel-body">
						{{ form.as_p }}
					</div>
				</div>
			</div>

			<div>
				<div class="col-lg-12 text-right">
					<input type="submit" class="btn btn-primary" name="submit" value="Guardar">
					<a role="button" class="btn btn-outline-danger" href="{{request.META.HTTP_REFERER}}">Cancelar</a>
				</div>
			</div>
		</form>
	</div>
</div>
</div>


{% endblock cuerpo %}

gastos/templates/proveedor_eliminar.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

  <h5> Eliminando Proveedor id:{{ object.pk }}</h5>

            <form method="post" action="{% url 'gastos:proveedor_eliminar' object.pk %}">{% csrf_token %}
                <p>Seguro que quieres eliminar este proveedor "{{ object }}"?</p>
                <input type="submit" class="btn btn-danger" value="Eliminar">
            </form>


</div>
      <div>
        <button type="button" class="btn btn-secondary justify-content-right" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

{% endblock cuerpo %}