gastos/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ListadoProveedores, DetalleProveedor, ModificarProveedor, NuevoProveedor, EliminarProveedor
from .views import ListadoGastos, DetalleGasto, ModificarGasto, NuevoGasto, EliminarGasto

app_name = 'gastos'

urlpatterns = [

    url(r'^listado_proveedores/$', ListadoProveedores.as_view(), name="listado_proveedores"),
    url(r'^detalle_proveedor/(?P<pk>.+)/$', DetalleProveedor.as_view(), name="detalle_proveedor"),
    url(r'^modificar_proveedor/(?P<pk>.+)/$', ModificarProveedor.as_view(), name="modificar_proveedor"),
    url(r'^nuevo_proveedor/', NuevoProveedor.as_view(), name="nuevo_proveedor"),
    url(r'^proveedor/(?P<pk>[0-9]+)/delete/$', EliminarProveedor.as_view(), name="proveedor_eliminar"),

    url(r'^listado_gastos/$', ListadoGastos.as_view(), name="listado_gastos"),
    url(r'^detalle_gasto/(?P<pk>.+)/$', DetalleGasto.as_view(), name="detalle_gasto"),
    url(r'^modificar_gasto/(?P<pk>.+)/$', ModificarGasto.as_view(), name="modificar_gasto"),
    url(r'^nuevo_gasto/', NuevoGasto.as_view(), name="nuevo_gasto"),
    url(r'^gasto/(?P<pk>[0-9]+)/delete/$', EliminarGasto.as_view(), name="gasto_eliminar"),
]

ozonemanagement/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.static import serve
from . import views

urlpatterns = [


url('albaranes/', include('albaranes.urls', namespace='albaranes')),
    url('articulos/', include('articulos.urls', namespace='articulos')),
    url('clientes/', include('clientes.urls', namespace='clientes')),
    url('pedidos/', include('pedidos.urls', namespace='pedidos')),
    url('almacen/', include('almacen.urls', namespace='almacen')),
    url('gastos/', include('gastos.urls', namespace='gastos')),
    url('profesionales/', include('profesionales.urls', namespace='profesionales')),


    path('admin/', admin.site.urls),
    url(r'^login/', auth_views.LoginView.as_view(), {'template_name': 'templates/login.html'}, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), {'template_name': 'templates/logged_out.html'}, name='logout'),
    url(r'^', views.index),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profesionales/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ListadoProfesionales, DetalleProfesional, ModificarProfesional, NuevoProfesional, EliminarProfesional
from .views import DocumentosNuevo,ModificarDocumento,EliminarDocumento, BajasNuevo, EliminarBaja, ModificarBaja
from . import views
from django.conf.urls.static import static

app_name = 'profesionales'

urlpatterns = [

    url(r'^listado_profesionales/$', ListadoProfesionales.as_view(), name="listado_profesionales"),
    url(r'^detalle_profesional/(?P<pk>.+)/$', DetalleProfesional.as_view(), name="detalle_profesional"),
    url(r'^modificar_profesional/(?P<pk>.+)/$', ModificarProfesional.as_view(), name="modificar_profesional"),
    url(r'^nuevo_profesional/', NuevoProfesional.as_view(), name="nuevo_profesional"),
    url(r'^profesional/(?P<pk>[0-9]+)/delete/$', EliminarProfesional.as_view(), name="profesional_eliminar"),

    url(r'^documentos_profesionales/(?P<pk>[0-9-]+)/$', views.documentos_profesionales, name="documentos_profesionales"),
    url(r'^documentos_nuevo/(?P<prof>[0-9]+)/$', DocumentosNuevo.as_view(), name="documentos_nuevo"),
    url(r'^documento_modificar/(?P<pk>[0-9]+)/$', ModificarDocumento.as_view(), name="documento_modificar"),
    url(r'^documento/(?P<pk>[0-9]+)/delete/$', EliminarDocumento.as_view(), name="doc_eliminar"),

    url(r'^bajas_profesionales/(?P<pk>[0-9-]+)/$', views.bajas_profesionales, name="bajas_profesionales"),
    url(r'^bajas_nuevo/(?P<prof>[0-9]+)/$', BajasNuevo.as_view(), name="bajas_nuevo"),
    url(r'^bajas_modificar/(?P<pk>[0-9]+)/$', ModificarBaja.as_view(), name="bajas_modificar"),
    url(r'^bajas/(?P<pk>[0-9]+)/delete/$', EliminarBaja.as_view(), name="baja_eliminar"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profesionales/forms.py
from django import forms
from .models import Profesional, Documentos, Bajas


class ProfesionalForm(forms.ModelForm):

    class Meta:
        model = Profesional
        fields='__all__'

    def __init__(self, *args, **kwargs):
        super(ProfesionalForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):

            self.fields[field].widget.attrs.update({
                'class': 'form-control border-primary'
            })



class DocuForm(forms.ModelForm):
    class Meta:
        model = Documentos
        fields = ('profesional', 'tipodocumento', 'etiqueta', 'fecha_documento', 'documento')

        fecha_documento = forms.DateField(
            widget = forms.DateInput(format='%m/%d/%Y'),
            input_formats=('%m/%d/%Y',)
        )


    def _init_(self, *args, **kwargs):
        super(DocuForm, self)._init_(*args, **kwargs)
        for field in iter(self.fields):

            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

            if field == 'profesional':
                self.fields['profesional'].widget.attrs['readonly']=True


class BajaForm(forms.ModelForm):
    class Meta:
        model = Bajas
        fields = ('profesional', 'etiqueta', 'fecha_documento', 'bajas')

        fecha_documento = forms.DateField(
            widget = forms.DateInput(format='%m/%d/%Y'),
            input_formats=('%m/%d/%Y',)
        )


    def _init_(self, *args, **kwargs):
        super(BajaForm, self)._init_(*args, **kwargs)
        for field in iter(self.fields):

            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

            if field == 'profesional':
                self.fields['profesional'].widget.attrs['readonly']=True

profesionales/views.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .forms import ProfesionalForm, DocuForm, BajaForm
from .models import Profesional, Documentos, Bajas
from django.urls import reverse_lazy
from django.urls import reverse
from django.shortcuts import render
import os
from django.conf import settings



class ListadoProfesionales(ListView):
    model = Profesional
    template_name = 'listado_profesionales.html'
    context_object_name ='profesionales'

class DetalleProfesional(DetailView):
    model = Profesional
    template_name = 'detalle_profesional.html'

class ModificarProfesional(UpdateView):
    model = Profesional
    template_name = 'modificar_profesional.html'
    form_class = ProfesionalForm
    success_url = reverse_lazy('profesionales:listado_profesionales')

class NuevoProfesional(CreateView):
    model = Profesional
    template_name = 'nuevo_profesional.html'
    form_class = ProfesionalForm
    success_url = reverse_lazy('profesionales:listado_profesionales')

class EliminarProfesional(DeleteView):
    model = Profesional
    template_name = 'profesional_eliminar.html'
    success_url = reverse_lazy('profesionales:listado_profesionales')





def documentos_profesionales(request,pk):
    ext =[".jpg", ".png", "gif", ",jpeg"]
    file_path= os.path.join(settings.DJANGO_ROOT)
    print (file_path)
    print("_"*50)
    docus = Documentos.objects.filter(profesional_id=pk)
    return render(request , 'documentos_profesionales.html', context={'docs': docus, 'img_extension': ext, 'path':file_path, 'pk': pk})

class DocumentosNuevo(CreateView):
        model = Documentos
        template_name = 'formulario_docu_profesionales.html'
        form_class = DocuForm
        prof = None
        success_url = None

        def get_object(self, queryset=None):
            return queryset.get(int(prof=self.prof))

        def form_valid(self, form):
            qsProf = Profesional.objects.get(id=self.kwargs['prof'])
            form.instance.profesional = qsProf
            DocumentosNuevo.success_url = reverse('profesionales:documentos_profesionales', kwargs={'pk': self.kwargs['prof']})

            return super(DocumentosNuevo, self).form_valid(form)

        def get(self, request, *args, **kwargs):
            context = locals()
            context['prof'] = self.kwargs['prof']
            context['form'] = self.form_class

            return render(request, 'formulario_docu_profesionales.html', context)


class EliminarDocumento(DeleteView):
    model = Documentos
    template_name = 'confirm_delete_profesionales.html'
    prof = None
    success_url = None

    def delete(self, request, *args, **kwargs):
        print("."*50)
        print (self.kwargs['pk'])
        qsDocumentos = Documentos.objects.get(id=self.kwargs['pk'])
        EliminarDocumento.success_url = reverse_lazy('profesionales:documentos_profesionales', kwargs={'pk': qsDocumentos.profesional_id})
        return super(EliminarDocumento, self).delete(request, *args, **kwargs)



class ModificarDocumento(UpdateView):
    model = Documentos
    template_name = 'formulario_editar_profesionales.html'
    form_class = DocuForm
    prof = None
    success_url= None

    def form_valid(self, form):
        qsDocumentos = Documentos.objects.get(id=self.kwargs['pk'])
        qsProf = Profesional.objects.get(id = qsDocumentos.profesional_id)
        form.instance.profesional = qsProf
        ModificarDocumento.success_url = reverse('profesionales:documentos_profesionales', kwargs={'pk': qsDocumentos.profesional_id})
        return super(ModificarDocumento, self).form_valid(form)


def bajas_profesionales(request,pk):
    ext =[".jpg", ".png", "gif", ",jpeg"]
    file_path= os.path.join(settings.DJANGO_ROOT)
    print (file_path)
    print("_"*50)
    bajas = Bajas.objects.filter(profesional_id=pk)
    return render(request , 'bajas_profesionales.html', context={'bajas': bajas, 'img_extension': ext, 'path':file_path, 'pk': pk})

class BajasNuevo(CreateView):
        model = Bajas
        template_name = 'formulario_bajas_profesionales.html'
        form_class = BajaForm
        prof = None
        success_url = None

        def get_object(self, queryset=None):
            return queryset.get(int(prof=self.prof))

        def form_valid(self, form):
            qsProf = Profesional.objects.get(id=self.kwargs['prof'])
            form.instance.profesional = qsProf
            BajasNuevo.success_url = reverse('profesionales:bajas_profesionales', kwargs={'pk': self.kwargs['prof']})

            return super(BajasNuevo, self).form_valid(form)

        def get(self, request, *args, **kwargs):
            context = locals()
            context['prof'] = self.kwargs['prof']
            context['form'] = self.form_class

            return render(request, 'formulario_bajas_profesionales.html', context)


class EliminarBaja(DeleteView):
    model = Bajas
    template_name = 'confirm_delete_bajas.html'
    prof = None
    success_url = None

    def delete(self, request, *args, **kwargs):
        print("."*50)
        print (self.kwargs['pk'])
        qsBajas = Bajas.objects.get(id=self.kwargs['pk'])
        EliminarBaja.success_url = reverse_lazy('profesionales:bajas_profesionales', kwargs={'pk': qsBajas.profesional_id})
        return super(EliminarBaja, self).delete(request, *args, **kwargs)



class ModificarBaja(UpdateView):
    model = Bajas
    template_name = 'formulario_editar_bajas.html'
    form_class = BajaForm
    prof = None
    success_url= None

    def form_valid(self, form):
        qsBajas = Bajas.objects.get(id=self.kwargs['pk'])
        qsProf = Profesional.objects.get(id = qsBajas.profesional_id)
        form.instance.profesional = qsProf
        ModificarBaja.success_url = reverse('profesionales:bajas_profesionales', kwargs={'pk': qsBajas.profesional_id})
        return super(ModificarBaja, self).form_valid(form)

profesionales/templates/bajas_profesionales.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}
{% with menubajas="1" pk=pk %}
	{% include "menuprofesionales.html" %}
{% endwith %}
<br>

<div class="row">
	<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card ">
		<div class="card">
			<div class="card-body">

				<a onclick="return abrir_modal('{% url 'profesionales:bajas_nuevo' prof=pk %}')">
	  				<span class="btn btn-info btn-sm">Agregar Bajas</span>
				</a>

				<h3 class="card-title"></h3>

                {% if bajas %}
					<div class="row">
						<div class="col"><p>Etiqueta</p></div>
						<div class="col"><p>Fecha</p></div>
						<div class="col"><p></p></div>
					</div>
					<hr>

					{% for 	baja in bajas %}
					<div class="row">
						<div class="col-sm-3 col-md-3 col-lg-3"><p>{{ baja.etiqueta }}</p></div>
						<div class="col-sm-3 col-md-3 col-lg-3 "><p>{{ baja.fecha_documento }}</p></div>
						<div class="col-sm-3 col-md-3 col-lg-5"><p>
							<a class="btn btn-outline-primary btn-sm"
										   data-toggle="collapse"
										   href="#baja{{ baja.id }}"
										   role="button"
										   aria-expanded="false"
										   aria-controls="baja{{ baja.id }}">ver
							</a>
							<a onclick="return abrir_modal('{% url 'profesionales:bajas_modificar' baja.pk%}')">
								<span class="btn btn-outline-info btn-sm">edit</span>
							</a>
							<a onclick="return abrir_modal('{% url 'profesionales:baja_eliminar' baja.pk%}')">
								<span class="btn btn-outline-danger btn-sm mdi mdi-delete"></span>
							</a></p>
						</div>
						</div>
			        {% endfor %}

					{% else %}
						No tiene bajas asignadas
					{% endif %}
				<hr>
			</div>
		</div>
	</div>



<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card " id="myGroup">

				  {% for baja in bajas %}
							  <div class="collapse" id="baja{{ baja.id }}" data-parent="#myGroup">
									 {{ baja.etiqueta  }} <hr>
								  <div class="card card-body">

										{% if not baja.bajas %}
											<img class="container" src="{%  static 'assets/images/not_found.png' %}" ></a>
										{% else %}
									  		<img class="container" src="{{ baja.bajas.url }}" ></a>
									  {% endif %}
								  </div>
							  </div>
				  {% endfor %}

</div>


</div> <!--  end row -->


<div id="popup" class="modal fade" role="dialog">  </div>


{% endblock cuerpo %}

{% block js %}


<script>
function abrir_modal(url)
{
	$('#popup').load(url, function()
	{
		$(this).modal('show');
	});
	return false;
}

function cerrar_modal()
{
	$('#popup').modal('hide');
	return false;
}




</script>

<!--  custom js for this page-->
<script src="{% static 'assets/js/shared/modal-demo.js' %}"></script>

{% endblock js %}

profesionales/templates/confirm_delete_bajas.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

          <h5> Eliminando Baja </h5>

          <form method="post" action="{% url 'profesionales:baja_eliminar' object.pk %}">{% csrf_token %}
                <p>Seguro que quieres eliminar esta baja ?</p>
                <input type="submit" class="btn btn-danger" value="Eliminar">
          </form>
      </div>
    </div>
  </div>
</div>

{% endblock cuerpo %}

profesionales/templates/confirm_delete_profesionales.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

            <h5> Eliminando documento </h5>

            <form method="post" action="{% url 'profesionales:doc_eliminar' object.pk %}">{% csrf_token %}
                <p>Seguro que quieres eliminar este documento ?</p>
                <input type="submit" class="btn btn-danger" value="Eliminar">
            </form>
      </div>
    </div>
  </div>
</div>

{% endblock cuerpo %}

profesionales/templates/documentos_profesionales.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}
{% with menudocumento="1" pk=pk %}
	{% include "menuprofesionales.html" %}
{% endwith %}
<br>

<div class="row">
	<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card ">
		<div class="card">
			<div class="card-body">

				<a onclick="return abrir_modal('{% url 'profesionales:documentos_nuevo' prof=pk %}')">
	  				<span class="btn btn-info btn-sm">Agregar Documentos</span>
				</a>


				<h3 class="card-title"></h3>


				{% if docs %}
					<div class="row">
						<div class="col"><p>Tipo</p></div>
						<div class="col"><p>Fecha</p></div>
						<div class="col"><p></p></div>
					</div>
					<hr>

					{% for 	doc in docs %}
					<div class="row">
						<div class="col-sm-3 col-md-3 col-lg-3"><p>{{ doc.tipodocumento }}</p></div>
						<div class="col-sm-3 col-md-3 col-lg-3 "><p>{{ doc.fecha_documento }}</p></div>
						<div class="col-sm-3 col-md-3 col-lg-5"><p>
							<a class="btn btn-outline-primary btn-sm"
										   data-toggle="collapse"
										   href="#doc{{ doc.id }}"
										   role="button"
										   aria-expanded="false"
										   aria-controls="doc{{ doc.id }}">ver
							</a>
							<a onclick="return abrir_modal('{% url 'profesionales:documento_modificar' doc.pk%}')">
								<span class="btn btn-outline-info btn-sm">edit</span>
							</a>
							<a onclick="return abrir_modal('{% url 'profesionales:doc_eliminar' doc.pk%}')">
								<span class="btn btn-outline-danger btn-sm mdi mdi-delete"></span>
							</a></p>
						</div>
						</div>
			        {% endfor %}

					{% else %}
						No tiene Documentos
					{% endif %}
				<hr>
			</div>
		</div>
	</div>



<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card " id="myGroup">

				  {% for doc in docs %}
							  <div class="collapse" id="doc{{ doc.id }}" data-parent="#myGroup">
									 {{ doc.etiqueta  }} <hr>
								  <div class="card card-body">

										{% if not doc.documento %}
											<img class="container" src="{%  static 'assets/images/not_found.png' %}" ></a>
										{% else %}
									  		<img class="container" src="{{ doc.documento.url }}" ></a>
									  {% endif %}
								  </div>
							  </div>
				  {% endfor %}

</div>


</div> <!--  end row -->


<div id="popup" class="modal fade" role="dialog">  </div>


{% endblock cuerpo %}

{% block js %}


<script>
function abrir_modal(url)
{
	$('#popup').load(url, function()
	{
		$(this).modal('show');
	});
	return false;
}

function cerrar_modal()
{
	$('#popup').modal('hide');
	return false;
}




</script>

<!--  custom js for this page-->
<script src="{% static 'assets/js/shared/modal-demo.js' %}"></script>

{% endblock js %}

profesionales/templates/formulario_bajas_profesionales.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

            <h6> Nueva Baja</h6>

         <form  role="form"  action="{% url 'profesionales:bajas_nuevo' prof=prof %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <p>{{ form.etiqueta.label }}</p>
                {{ form.etiqueta }}
                {{ form.etiqueta.errors }}
            </div>
            <div class="form-group">
                <p>{{ form.fecha_documento.label }}</p>
                {{ form.fecha_documento }}
                {{ form.fecha_documento.errors }}
            </div>
            <div class="form-group">
                <p>{{ form.bajas.label }}</p>
                {{ form.bajas }}
                {{ form.bajas.errors }}
            </div>
            <div class="actions">
                <button type="submit" class="btn btn-success">Enviar</button>
            </div>
         </form>
      </div>
    </div>
  </div>
</div>

{% endblock cuerpo %}

profesionales/templates/formulario_docu_profesionales.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

            <h6> Nuevo Documento</h6>

         <form  role="form"  action="{% url 'profesionales:documentos_nuevo' prof=prof %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <p>{{ form.tipodocumento.label }}</p>
                {{ form.tipodocumento}}
                {{ form.tipodocumento.errors }}
            </div>
            <div class="form-group">
                <p>{{ form.etiqueta.label }}</p>
                {{ form.etiqueta }}
                {{ form.etiqueta.errors }}
            </div>
            <div class="form-group">
                <p>{{ form.fecha_documento.label }}</p>
                {{ form.fecha_documento }}
                {{ form.fecha_documento.errors }}
            </div>
            <div class="form-group">
                <p>{{ form.documento.label }}</p>
                {{ form.documento }}
                {{ form.documento.errors }}
            </div>


            <div class="actions">
                <button type="submit" class="btn btn-success">Enviar</button>
            </div>
         </form>
      </div>
    </div>
  </div>
</div>

{% endblock cuerpo %}

profesionales/templates/formulario_editar_bajas.html
{% load staticfiles %}
{% block cuerpo %}

<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <div class="modal-body">

        <h6> Editando Bajas </h6>

        <form  role="form" action="{% url 'profesionales:bajas_modificar' object.pk %}"   method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <p>{{ form.etiqueta.label }}</p>
                {{ form.etiqueta }}
                {{ form.etiqueta.errors }}
            </div>
            <div class="form-group">
                <p>{{ form.fecha_documento.label }}</p>
                {{ form.fecha_documento }}
                {{ form.fecha_documento.errors }}
            </div>
            <div class="form-group">
                <p>{{ form.bajas.label }}</p>
                {{ form.bajas }}
                {{ form.bajas.errors }}
            </div>
            <div class="actions">
                <button type="submit" class="btn btn-success">Enviar</button>
            </div>
        </form>
    </div>
    </div>
  </div>
</div>

{% endblock cuerpo %}

profesionales/templates/listado_profesionales.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}

      <!-- partial -->

<style>
.dataTables_wrapper .dataTable .btn{
     padding: 0.4rem 0.9rem!important;
    vertical-align: top;
}
</style>


<div class="row">
  <div class="col-md-12">
            <div class="card" >
              <div class="card-body">
                  <h3 class="card-title">Listado de Profesionales</h3>
                  <p class="card-description">  </p>
                <div class="row">
                  <div class="col-12 table-responsive">
                    <table id="tabla" class="table">
                      <thead>
                        <tr>

                             <th>Nombre Completo</th>
                             <th>DNI </th>
                             <th>Tipo Contrato</th>
                             <th>Fecha Vencimiento</th>
                             <th> <a role="button" class="btn btn-outline-warning btn-sm" href="{% url 'profesionales:nuevo_profesional' %}">Nuevo Profesional</a></th>
                        </tr>
                      </thead>

                      <tbody>

                        {% for 	prof in profesionales %}

                            <tr>
                                <td>{{ prof.nombre | default_if_none:"" | truncatechars:25 }}&nbsp;{{ prof.apellidos | default_if_none:"" | truncatechars:25 }}</td>
                                <td>{{ prof.num_documento | default_if_none:"" | truncatechars:25 }}</td>
                                <td>{{ prof.tipo_contrato_display | default_if_none:"" }}</td>
                                <td>{{ prof.fecha_vencimiento | default_if_none:"" }} </td>
                                <td>
                                    <a role="button" class="btn btn-outline-primary btn-sm" href="{% url 'profesionales:detalle_profesional' prof.pk %}">ver</a>
                                    <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'profesionales:modificar_profesional' prof.pk %}">modificar</a>
                                    <a onclick="return abrir_modal('{% url 'profesionales:profesional_eliminar' prof.pk %}')">
                                        <span class="btn btn-outline-danger mdi mdi-delete"></span></a>
                                </td>
                            </tr>
			            {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

  </div>
</div>
<div id="popup" class="modal fade" role="dialog">


</div>
{% endblock cuerpo %}

{% block js %}

<script>
function abrir_modal(url)
{
	$('#popup').load(url, function()
	{
		$(this).modal('show');
	});
	return false;
}

function cerrar_modal()
{
	$('#popup').modal('hide');
	return false;
}

$(document).ready(function()
{
    var table = $('#tabla').dataTable( {
        "language": {
        	url: "/static/assets/localizacion/es_ES.json"
        }
    } );
});
</script>


    <!-- Custom js for this page
    <script src="{% static '/assets/js/shared/data-table.js' %}"></script>-->
          <script src="{% static 'assets/js/shared/modal-demo.js' %}"></script>
   <!--<script src="{% static 'assets/js/shared/jquery.dataTables.min.js' %}"></script>-->
   <!-- End custom js for this page-->

{% endblock js %}

profesionales/templates/menuprofesionales.html
<nav class="navbar  bg-light text-center nav-bottom ">

	<div class="container d-flex justify-content-center">
	<ul class="nav nav-tabs tab-solid tab-solid" role="tablist">

		<li class="nav-item"><a class="btn btn-outline-primary {% if menudetalle %}btn-outline-primary active{% endif %}" href="{% url 'profesionales:detalle_profesional' pk %}">Detalles</a></li>
		<li class="nav-item"><a class="btn btn-outline-primary {% if menudocumento %}btn-outline-primary active{% endif %}" href="{% url 'profesionales:documentos_profesionales' pk %}">Documentos </a></li>
		<li class="nav-item"><a class="btn btn-outline-primary {% if menubajas %}btn-outline-primary active{% endif %}" href="{% url 'profesionales:bajas_profesionales' pk %}">Bajas </a></li>
    </ul>

    </div>
</nav>