albaranes/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ListadoAlbaranes,ModificarAlbaran,NuevoAlbaran,EliminarAlbaran
from . import views

app_name = 'albaranes'

urlpatterns = [

    url(r'^listado_albaranes/$', ListadoAlbaranes.as_view(), name="listado_albaranes"),
    url(r'^detalle_albaran/(?P<pk>.+)/$', views.DetalleAlbaran, name="detalle_albaran"),
    url(r'^modificar_albaran/(?P<pk>.+)/$', ModificarAlbaran.as_view(), name="modificar_albaran"),
    url(r'^nuevo_albaran/', NuevoAlbaran.as_view(), name="nuevo_albaran"),
    url(r'^albaran/(?P<pk>[0-9]+)/delete/$', EliminarAlbaran.as_view(), name="albaran_eliminar"),


]

articulos/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import ListadoArticulos, DetalleArticulo, ModificarArticulo, NuevoArticulo, EliminarArticulo
from .views import ListadoCategorias, DetalleCategoria, ModificarCategoria, NuevaCategoria,EliminarCategoria

app_name = 'articulos'

urlpatterns = [
    url(r'^listado_articulos/$', ListadoArticulos.as_view(), name="listado_articulos"),
    url(r'^detalle/(?P<pk>.+)/$', DetalleArticulo.as_view(), name="detalle_articulo"),
    url(r'^modificar/(?P<pk>.+)/$', ModificarArticulo.as_view(), name="modificar_articulo"),
    url(r'^nuevo_articulo/', NuevoArticulo.as_view(), name="nuevo_articulo"),
    url(r'^articulo/(?P<pk>[0-9]+)/delete/$', EliminarArticulo.as_view(), name="articulo_eliminar"),

    url(r'^listado_categorias/$', ListadoCategorias.as_view(), name="listado_categorias"),
    url(r'^detalle_categoria/(?P<pk>.+)/$', DetalleCategoria.as_view(), name="detalle_categoria"),
    url(r'^modificar_categoria/(?P<pk>.+)/$', ModificarCategoria.as_view(), name="modificar_categoria"),
    url(r'^nueva_categoria /', NuevaCategoria.as_view(), name="nueva_categoria"),
    url(r'^categoria/(?P<pk>[0-9]+)/delete/$', EliminarCategoria.as_view(), name="categoria_eliminar"),





]

gastos/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ListadoProveedores, DetalleProveedor, ModificarProveedor, NuevoProveedor, EliminarProveedor
from .views import ListadoGastos, DetalleGasto, ModificarGasto, NuevoGasto, EliminarGasto

app_name = 'gastos'

urlpatterns = [

    url(r'^listado_proveedores/$', ListadoProveedores.as_view(), name="listado_proveedores"),
    url(r'^detalle_proveedor/(?P<pk>.+)/$', DetalleProveedor.as_view(), name="detalle_proveedor"),
    url(r'^modificar_proveedor/(?P<pk>.+)/$', ModificarProveedor.as_view(), name="modificar_proveedor"),
    url(r'^nuevo_proveedor/', NuevoProveedor.as_view(), name="nuevo_proveedor"),
    url(r'^proveedor/(?P<pk>[0-9]+)/delete/$', EliminarProveedor.as_view(), name="proveedor_eliminar"),

    url(r'^listado_gastos/$', ListadoGastos.as_view(), name="listado_gastos"),
    url(r'^detalle_gasto/(?P<pk>.+)/$', DetalleGasto.as_view(), name="detalle_gasto"),
    url(r'^modificar_gasto/(?P<pk>.+)/$', ModificarGasto.as_view(), name="modificar_gasto"),
    url(r'^nuevo_gasto/', NuevoGasto.as_view(), name="nuevo_gasto"),
    url(r'^gasto/(?P<pk>[0-9]+)/delete/$', EliminarGasto.as_view(), name="gasto_eliminar"),
]

ozonemanagement/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.static import serve
from . import views

urlpatterns = [


url('albaranes/', include('albaranes.urls', namespace='albaranes')),
    url('articulos/', include('articulos.urls', namespace='articulos')),
    url('clientes/', include('clientes.urls', namespace='clientes')),
    url('pedidos/', include('pedidos.urls', namespace='pedidos')),
    url('almacen/', include('almacen.urls', namespace='almacen')),
    url('gastos/', include('gastos.urls', namespace='gastos')),
    url('profesionales/', include('profesionales.urls', namespace='profesionales')),


    path('admin/', admin.site.urls),
    url(r'^login/', auth_views.LoginView.as_view(), {'template_name': 'templates/login.html'}, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), {'template_name': 'templates/logged_out.html'}, name='logout'),
    url(r'^', views.index),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

albaranes/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
import django.utils.timezone
from datetime import datetime
from django import forms


class Albaran(TimeStampedModel):

#DATOS SOBRE ALBARANES

    cod_albaran = models.CharField(max_length=30, null=True, blank=True)
    descripcion = models.CharField(max_length=255, null=True, blank=True)
    fecha = models.DateField(default=django.utils.timezone.now, editable=True)

    #Cliente

    cliente = models.ForeignKey("clientes.Cliente", db_index=True, on_delete=models.CASCADE, null=True, blank=True)


   #Profesional

    profesional = models.ForeignKey("profesionales.profesional", db_index=True, on_delete=models.CASCADE, null=True, blank=True)

    #Pedido

    pedido = models.ForeignKey("pedidos.Pedido", db_index=True, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return  (self.cod_albaran)

    class Meta:
        verbose_name = "Albaran"
        verbose_name_plural = "Albaranes"
        ordering = ['-created']

albaranes/forms.py
from django import forms
from .models import Albaran

class AlbaranForm(forms.ModelForm):

    class Meta:
        model = Albaran
        fields='__all__'

    def __init__(self, *args, **kwargs):
        super(AlbaranForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):

            self.fields[field].widget.attrs.update({
                'class': 'form-control border-primary'
            })

albaranes/views.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from .forms import AlbaranForm
from pedidos.models import Pedido
from .models import Albaran
from articulos .models import ArticuloPedido
from clientes.models import Cliente
from django.shortcuts import render



class ListadoAlbaranes(ListView):
    model = Albaran
    template_name = 'listado_albaranes.html'
    context_object_name ='albaranes'


class ModificarAlbaran(UpdateView):
    model = Albaran
    template_name = 'modificar_albaran.html'
    form_class = AlbaranForm
    success_url = reverse_lazy('albaranes:listado_albaranes')

class NuevoAlbaran(CreateView):
    model = Albaran
    template_name = 'nuevo_albaran.html'
    form_class = AlbaranForm
    success_url = reverse_lazy('albaranes:listado_albaranes')


class EliminarAlbaran(DeleteView):
    model=Albaran
    template_name = 'albaran_eliminar.html'
    success_url = reverse_lazy('albaranes:listado_albaranes')



def DetalleAlbaran(request, pk):

    albaran = Albaran.objects.get(pk=pk)

    articulo = ArticuloPedido.objects.filter(cod_pedido=albaran.pedido)

    return render(request, 'detalle_albaran.html', context={'albaran': albaran,'articulo': articulo, 'pk':pk})

albaranes/templates/articulo_eliminar.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

  <h5> Eliminando Articulo id:{{ object.pk }}</h5>

            <form method="post" action="{% url 'articulos:articulo_eliminar' object.pk %}">{% csrf_token %}
                <p>Seguro que quieres eliminar este articulo "{{ object }}"?</p>
                <input type="submit" class="btn btn-danger" value="Eliminar">
            </form>


</div>
      <div>
        <button type="button" class="btn btn-secondary justify-content-right" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

{% endblock cuerpo %}

albaranes/templates/categoria_eliminar.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

  <h5> Eliminando Categoria id:{{ object.pk }}</h5>

            <form method="post" action="{% url 'articulos:categoria_eliminar' object.pk %}">{% csrf_token %}
                <p>Seguro que quieres eliminar esta categoria "{{ object }}"?</p>
                <input type="submit" class="btn btn-danger" value="Eliminar">
            </form>


</div>
      <div>
        <button type="button" class="btn btn-secondary justify-content-right" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

{% endblock cuerpo %}

albaranes/templates/detalle_articulo.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">


          <h5 class="card-title"><i class="mdi mdi-receipt text-primary icon-md mr-4 mr-sm-4">
					</i>Detalle del Articulo
		  </h5>
					<hr>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

		<div class="modal-body">

					<hr>

					<p>Nombre:		&nbsp;   <label>{{ articulo.nombre | default_if_none:"" | truncatechars:50}}</label></p>
					<p>Proveedor:	&nbsp;	<label>{{ articulo.proveedor | default_if_none:"" | truncatechars:50}}</label></p>
					<p>Cat. Articulo:   &nbsp;<label>{{ articulo.categoria | default_if_none:"" | truncatechars:50}}</label></p>
					<p>Precio:   		&nbsp;<label>{{ articulo.precio | default_if_none:"" | truncatechars:50}}</label></p>



	  </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-outline-danger" data-dismiss="modal">cerrar</button>
		</div>

	</div>
  </div>
</div>
{% endblock cuerpo %}

albaranes/templates/detalle_categoria.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">


          <h5 class="card-title"><i class="mdi mdi-receipt text-primary icon-md mr-4 mr-sm-4">
					</i>Detalle de la Categoria
		  </h5>
					<hr>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

		<div class="modal-body">

					<hr>

					<p>Nombre:		&nbsp;   <label>{{ categoria.nombre | default_if_none:"" | truncatechars:50}}</label></p>
					<p>Descripción:		&nbsp;   <label>{{ categoria.descripcion | default_if_none:"" | truncatechars:100}}</label></p>


	  </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-outline-danger" data-dismiss="modal">cerrar</button>
		</div>

	</div>
  </div>
</div>
{% endblock cuerpo %}

albaranes/templates/listado_articulos.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}

{% with menuarticulo="1" pk=articulo.pk %}
	{% include "menuarticulos.html" %}
{% endwith %}

      <!-- partial -->

<style>
.dataTables_wrapper .dataTable .btn{
     padding: 0.4rem 0.9rem!important;
    vertical-align: top;
}
</style>


<div class="row">
  <div class="col-md-12">
            <div class="card" >
              <div class="card-body">
                  <h3 class="card-title">Listado de Articulos</h3>
                  <p class="card-description"></p>
                <div class="row">
                  <div class="col-12 table-responsive">
                    <table id="tabla" class="table">
                      <thead>
                        <tr>

                         <th>Cat. Articulo</th>
                         <th>Artículo </th>
                         <th>Proveedor</th>
                         <th>Precio</th>

                         <th> <a role="button" class="btn btn-outline-warning btn-sm" href="{% url 'articulos:nuevo_articulo' %}">Nuevo Artículo</a></th>


                        </tr>
                      </thead>

                      <tbody>

                        {% for 	item in articulos %}

                            <tr>

                                <td>{{ item.categoria | default_if_none:"" | truncatechars:30 }}</td>
                                <td>{{ item.nombre | default_if_none:"" | truncatechars:30 }}</td>
                                <td>{{ item.proveedor | default_if_none:"" | truncatechars:30}}</td>
                                <td>{{ item.precio | default_if_none:"" }} &nbsp; </td>
                                <td>
                                    <a onclick="return abrir_modal('{% url 'articulos:detalle_articulo' item.pk %}')"> <span class="btn btn-primary btn-sm">Detalles</span></a>
                                    <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'articulos:modificar_articulo' item.pk %}">Editar</a>
                                    <a onclick="return abrir_modal('{% url 'articulos:articulo_eliminar' item.pk %}')">
                                        <span class="btn btn-outline-danger mdi mdi-delete"></span></a>
                                </td>
                            </tr>
			            {% endfor %}

                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

  </div>
</div>
<div id="popup" class="modal fade" role="dialog">


</div>
{% endblock cuerpo %}

{% block js %}

<script>
function abrir_modal(url)
{
	$('#popup').load(url, function()
	{
		$(this).modal('show');
	});
	return false;
}

function cerrar_modal()
{
	$('#popup').modal('hide');
	return false;
}

$(document).ready(function()
{
    var table = $('#tabla').dataTable( {
        "language": {
        	url: "/static/assets/localizacion/es_ES.json"
        }
    } );
});
</script>


    <!-- Custom js for this page
    <script src="{% static '/assets/js/shared/data-table.js' %}"></script>-->
          <script src="{% static 'assets/js/shared/modal-demo.js' %}"></script>
   <!--<script src="{% static 'assets/js/shared/jquery.dataTables.min.js' %}"></script>-->
   <!-- End custom js for this page-->

{% endblock js %}

albaranes/templates/listado_categorias.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}

{% with menucategorias="1" pk=categoria.pk %}
	{% include "menuarticulos.html" %}
{% endwith %}

      <!-- partial -->

<style>
.dataTables_wrapper .dataTable .btn{
     padding: 0.4rem 0.9rem!important;
    vertical-align: top;
}
</style>


<div class="row">
  <div class="col-md-12">
            <div class="card" >
              <div class="card-body">
                  <h3 class="card-title">Listado de Categorias</h3>
                  <p class="card-description">  </p>
                <div class="row">
                  <div class="col-12 table-responsive">
                    <table id="tabla" class="table">
                      <thead>
                        <tr>

                         <th>Nombre </th>
                         <th>Descripción</th>

                         <th> <a role="button" class="btn btn-outline-warning btn-sm" href="{% url 'articulos:nueva_categoria' %}">Nueva Categoría</a></th>


                        </tr>
                      </thead>

                      <tbody>

                        {% for 	cat in categorias %}

                            <tr>

                                <td>{{ cat.nombre | default_if_none:"" | truncatechars:30 }}</td>
                                <td>{{ cat.descripcion | default_if_none:"" | truncatechars:70 }}</td>
                                <td>
                                    <a onclick="return abrir_modal('{% url 'articulos:detalle_categoria' cat.pk %}')">
                                        <span class="btn btn-primary btn-sm">Detalles</span></a>
                                    <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'articulos:modificar_categoria' cat.pk %}">Editar</a>

                                    <a onclick="return abrir_modal('{% url 'articulos:categoria_eliminar' cat.pk %}')">
                                        <span class="btn btn-outline-danger mdi mdi-delete"></span></a>
                                </td>
                            </tr>
			            {% endfor %}

                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

  </div>
</div>
<div id="popup" class="modal fade" role="dialog">


</div>
{% endblock cuerpo %}

{% block js %}

<script>
function abrir_modal(url)
{
	$('#popup').load(url, function()
	{
		$(this).modal('show');
	});
	return false;
}

function cerrar_modal()
{
	$('#popup').modal('hide');
	return false;
}

$(document).ready(function()
{
    var table = $('#tabla').dataTable( {
        "language": {
        	url: "/static/assets/localizacion/es_ES.json"
        }
    } );
});
</script>


    <!-- Custom js for this page
    <script src="{% static '/assets/js/shared/data-table.js' %}"></script>-->
          <script src="{% static 'assets/js/shared/modal-demo.js' %}"></script>
   <!--<script src="{% static 'assets/js/shared/jquery.dataTables.min.js' %}"></script>-->
   <!-- End custom js for this page-->

{% endblock js %}

albaranes/templates/menuarticulos.html
<nav class="navbar  bg-light text-center nav-bottom ">

	<div class="container d-flex justify-content-center">
	<ul class="nav nav-tabs tab-solid tab-solid" role="tablist">
		<li class="nav-item"><a class="btn btn-outline-primary " href="{% url 'articulos:listado_categorias' %}"> Categorias</a></li>
		<li class="nav-item"><a class="btn btn-outline-primary" href="{% url 'articulos:listado_articulos' %}"> Articulos</a></li>
		<li class="nav-item"><a class="btn btn-outline-primary" href="{% url 'gastos:listado_proveedores' %}"> Proveedores</a></li>
    </ul>

    </div>
</nav>

albaranes/templates/modificar_articulo.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}


                    <div class="container">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Modificando Articulo</h3>
                            <p class="card-description">  </p>
                        <form role="form" action="{% url 'articulos:modificar_articulo' object.pk %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <div>
                                <div class="col-lg-12 text-right">
                                    <input type="submit" class="btn btn-outline-success" name="submit" value="Guardar">
                                    <a role="button" class="btn btn-outline-danger" href="{{request.META.HTTP_REFERER}}">Cancelar</a>

                                </div>
                            </div>
                        </form>
                      </div>
                    </div>
                    </div>

{% endblock cuerpo %}

albaranes/templates/modificar_categoria.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}


                    <div class="container">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Modificando Categoria</h3>
                            <p class="card-description">  </p>
                        <form role="form" action="{% url 'articulos:modificar_categoria' object.pk %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <div>
                                <div class="col-lg-12 text-right">
                                    <input type="submit" class="btn btn-outline-success" name="submit" value="Guardar">
                                    <a role="button" class="btn btn-outline-danger" href="{{request.META.HTTP_REFERER}}">Cancelar</a>

                                </div>
                            </div>
                        </form>
                      </div>
                    </div>
                    </div>

{% endblock cuerpo %}

albaranes/templates/nueva_categoria.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}

<div class="container">
<div class="card">
    <div class="card-body">
		<form class="forms-group" role="form" action="{% url 'articulos:nueva_categoria' %}" method="post" enctype="multipart/form-data" >
			<h3 class="card-title">Nueva Categoria</h3>
            <p class="card-description">  </p>

            <div class="body">
				{% csrf_token %}
				<div class="panel panel-default">
					<div class="panel-body">
						{{ form.as_p }}
					</div>
				</div>
			</div>

			<div>
				<div class="col-lg-12 text-right">
					<input type="submit" class="btn btn-primary" name="submit" value="Guardar">
					<a role="button" class="btn btn-outline-danger" href="{{request.META.HTTP_REFERER}}">Cancelar</a>
				</div>
			</div>
		</form>
	</div>
</div>
</div>


{% endblock cuerpo %}

albaranes/templates/nuevo_articulo.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}

<div class="container">
<div class="card">
    <div class="card-body">
		<form class="forms-group" role="form" action="{% url 'articulos:nuevo_articulo' %}" method="post" enctype="multipart/form-data" >
			<h3 class="card-title">Nuevo Articulo</h3>
            <p class="card-description">  </p>

            <div class="body">
				{% csrf_token %}
				<div class="panel panel-default">
					<div class="panel-body">
						{{ form.as_p }}
					</div>
				</div>
			</div>

			<div>
				<div class="col-lg-12 text-right">
					<input type="submit" class="btn btn-primary" name="submit" value="Guardar">
					<a role="button" class="btn btn-outline-danger" href="{{request.META.HTTP_REFERER}}">Cancelar</a>
				</div>
			</div>
		</form>
	</div>
</div>
</div>


{% endblock cuerpo %}