clientes/urls.py
from django.conf.urls import url
from django.conf import settings
from .views import ListadoClientes, ModificarCliente, DetalleCliente , NuevoCliente , EliminarCliente,ModificarDocumento,EliminarDocumento
from .views import  DocumentosNuevo, FotoNueva, ModificarFoto, EliminarFoto
from . import views
from django.conf.urls.static import static

app_name = 'clientes'

urlpatterns = [

    url(r'^listado_clientes/$', ListadoClientes.as_view(), name="listado_clientes"),
    url(r'^detalle_cliente/(?P<pk>.+)/$', DetalleCliente.as_view(), name="detalle_cliente"),
    url(r'^modificar_cliente/(?P<pk>.+)/$', ModificarCliente.as_view(), name="modificar_cliente"),
    url(r'^nuevo_cliente/', NuevoCliente.as_view(), name="nuevo_cliente"),
    url(r'^cliente/(?P<pk>[0-9]+)/delete/$', EliminarCliente.as_view(), name="cliente_eliminar"),


    url(r'^documentos_cliente/(?P<pk>[0-9-]+)/$', views.documentos_cliente, name="documentos_cliente"),
    url(r'^documentos_nuevo/(?P<client>[0-9]+)/$', DocumentosNuevo.as_view(), name="documentos_nuevo"),
    url(r'^documento_modificar/(?P<pk>[0-9]+)/$', ModificarDocumento.as_view(), name="documento_modificar"),
    url(r'^documento/(?P<pk>[0-9]+)/delete/$', EliminarDocumento.as_view(), name="documento_eliminar"),

    url(r'^fotos_cliente/(?P<pk>[0-9-]+)/$', views.fotos_cliente, name="fotos_cliente"),
    url(r'^foto_nueva/(?P<client>[0-9]+)/$', FotoNueva.as_view(), name="foto_nueva"),
    url(r'^foto_modificar/(?P<pk>[0-9]+)/$', ModificarFoto.as_view(), name="foto_modificar"),
    url(r'^foto/(?P<pk>[0-9]+)/delete/$', EliminarFoto.as_view(), name="foto_eliminar"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gastos/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import ListadoProveedores, DetalleProveedor, ModificarProveedor, NuevoProveedor, EliminarProveedor
from .views import ListadoGastos, DetalleGasto, ModificarGasto, NuevoGasto, EliminarGasto

app_name = 'gastos'

urlpatterns = [

    url(r'^listado_proveedores/$', ListadoProveedores.as_view(), name="listado_proveedores"),
    url(r'^detalle_proveedor/(?P<pk>.+)/$', DetalleProveedor.as_view(), name="detalle_proveedor"),
    url(r'^modificar_proveedor/(?P<pk>.+)/$', ModificarProveedor.as_view(), name="modificar_proveedor"),
    url(r'^nuevo_proveedor/', NuevoProveedor.as_view(), name="nuevo_proveedor"),
    url(r'^proveedor/(?P<pk>[0-9]+)/delete/$', EliminarProveedor.as_view(), name="proveedor_eliminar"),

    url(r'^listado_gastos/$', ListadoGastos.as_view(), name="listado_gastos"),
    url(r'^detalle_gasto/(?P<pk>.+)/$', DetalleGasto.as_view(), name="detalle_gasto"),
    url(r'^modificar_gasto/(?P<pk>.+)/$', ModificarGasto.as_view(), name="modificar_gasto"),
    url(r'^nuevo_gasto/', NuevoGasto.as_view(), name="nuevo_gasto"),
    url(r'^gasto/(?P<pk>[0-9]+)/delete/$', EliminarGasto.as_view(), name="gasto_eliminar"),
]

ozonemanagement/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.static import serve
from . import views

urlpatterns = [


url('albaranes/', include('albaranes.urls', namespace='albaranes')),
    url('articulos/', include('articulos.urls', namespace='articulos')),
    url('clientes/', include('clientes.urls', namespace='clientes')),
    url('pedidos/', include('pedidos.urls', namespace='pedidos')),
    url('almacen/', include('almacen.urls', namespace='almacen')),
    url('gastos/', include('gastos.urls', namespace='gastos')),
    url('profesionales/', include('profesionales.urls', namespace='profesionales')),


    path('admin/', admin.site.urls),
    url(r'^login/', auth_views.LoginView.as_view(), {'template_name': 'templates/login.html'}, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), {'template_name': 'templates/logged_out.html'}, name='logout'),
    url(r'^', views.index),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/models.py
from django.db import models
from datetime import datetime
from django_extensions.db.models import TimeStampedModel
import django.utils.timezone


PROFESIONAL = 1
PARTICULAR = 2

TIPOCLIENTE = (
    (PROFESIONAL, 'Profesional'),
    (PARTICULAR, 'Particular'),
)

NIF = 1
NIE = 2
CIF = 3

TIPODOCUMENTO = (
    (NIF, 'Nif'),
    (NIE, 'Nie'),
    (CIF, 'Cif'),
)



INDEFINIDO = 1
HOMBRE = 2
MUJER = 3

SEXO = (
    (INDEFINIDO, 'Indefinido'),
    (HOMBRE, 'Hombre'),
    (MUJER, 'Mujer'),
)



class Provincias(TimeStampedModel):
    nombre = models.CharField(max_length=255)
    pais = models.CharField(max_length=255)
    cod_provincia = models.CharField(max_length=255)


    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "provincia"
        verbose_name_plural = "provincias"
        ordering = ['-created']

class Poblacion(TimeStampedModel):
    nombre = models.CharField(max_length=255)
    cod_poblacion = models.CharField(max_length=255)
    cod_provincia = models.CharField(max_length=255)
    provincias = models.ForeignKey("Provincias", db_index=True, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "poblacion"
        verbose_name_plural = "poblacion"
        ordering = ['-created']


class Cliente(TimeStampedModel):

    #INFORMACION SOBRE EL CLIENTE

    tipo_cliente = models.IntegerField(default=PROFESIONAL, choices=TIPOCLIENTE, db_index=True, null=True, blank=True)
    nombre = models.CharField(max_length=255, null=True, blank=True)
    apellidos = models.CharField(max_length=255)
    tipo_documento = models.IntegerField(default=CIF, choices=TIPODOCUMENTO, db_index=True, null=True, blank=True)
    num_documento = models.CharField(max_length=9, blank=True, null=True)
    fecha_nacimiento = models.DateField(default=django.utils.timezone.now, editable=True,blank=True, null=True)
    dir_calle = models.CharField(null=True, max_length=255, blank=True, verbose_name="Calle")
    dir_numero = models.CharField(null=True, max_length=255, blank=True, verbose_name="Número")
    dir_piso = models.CharField(null=True, max_length=255, blank=True, verbose_name="Piso/Planta")
    codigo_postal = models.CharField(null=True, blank=True, max_length=8)
    provincias = models.ForeignKey("provincias", db_index=True, on_delete=models.CASCADE, null=True, blank=True)
    poblacion = models.ForeignKey("poblacion", db_index=True, on_delete=models.CASCADE, null=True, blank=True)
    email = models.EmailField(max_length=255)
    telefono = models.CharField(max_length=20, null=True, blank=True,verbose_name="Télefono")
    movil = models.CharField(max_length=20, null=True, blank=True)
    web = models.CharField(max_length=255, blank=True, null=True)
    profesion = models.CharField(max_length=50, blank=True, null=True)
    fecha_alta = models.DateField(default=django.utils.timezone.now, editable=True, blank=True, null=True)
    sexo = models.IntegerField(default=INDEFINIDO, choices=SEXO, db_index=True, null=True, blank=True)


    def __str__(self):
        return "{} {}".format(self.nombre, self.apellidos)

    def tipo_documento_display(self):
        return '%s' % (self.get_tipo_documento_display())

    def num_documento_display(self):
        return '%s' % (self.get_num_documento_display())



    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ['-created']



class TipoDocumentos(TimeStampedModel):
    code = models.PositiveIntegerField()
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "tipo documento"
        verbose_name_plural = "tipo documentos"
        ordering = ['-created']



class Documentos(TimeStampedModel):
    cliente = models.ForeignKey("Cliente", db_index=True, on_delete=models.CASCADE, null=True, blank=True)
    tipodocumento = models.ForeignKey("TipoDocumentos", db_index=True, on_delete=models.CASCADE, null=True, blank=True)
    etiqueta = models.CharField(max_length=255)
    fecha_documento = models.DateField(default= django.utils.timezone.now, editable=True)
    documento = models.FileField(upload_to='documentos_cliente', null=True, blank=True)

    def __str__(self):
        return self.etiqueta

    def extension(self):
        name, extension = os.path.splitext(self.documento.name)
        return extension

    class Meta:
        verbose_name = "documento"
        verbose_name_plural = "documentos"
        ordering = ['-created']


class Fotos(TimeStampedModel):
    cliente = models.ForeignKey("Cliente", db_index=True, on_delete=models.CASCADE, null=True, blank=True)
    etiqueta = models.CharField(max_length=255)
    fecha_foto = models.DateField(default= django.utils.timezone.now, editable=True)
    foto = models.ImageField(upload_to='imagenes', null=True, blank=True)

    def __str__(self):
        return self.etiqueta

    def extension(self):
        name, extension = os.path.splitext(self.imagenes.name)
        return extension



    class Meta:
        verbose_name = "foto"
        verbose_name_plural = "fotos"
        ordering = ['-created']

clientes/forms.py
from django import forms
from .models import Cliente, Documentos, Fotos


class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields='__all__'

    def __init__(self, *args, **kwargs):
        super(ClienteForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):

            self.fields[field].widget.attrs.update({
                'class': 'form-control border-primary'
            })






class DocuForm(forms.ModelForm):
    class Meta:
        model = Documentos
        fields = ('cliente', 'tipodocumento', 'etiqueta', 'fecha_documento', 'documento')

        fecha_documento = forms.DateField(
            widget = forms.DateInput(format='%m/%d/%Y'),
            input_formats=('%m/%d/%Y',)
        )


    def _init_(self, *args, **kwargs):
        super(DocuForm, self)._init_(*args, **kwargs)
        for field in iter(self.fields):

            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

            if field == 'cliente':
                self.fields['cliente'].widget.attrs['readonly']=True


class FotoForm(forms.ModelForm):
    class Meta:
        model = Fotos
        fields = ('cliente', 'etiqueta', 'fecha_foto', 'foto')

        fecha_foto = forms.DateField(
            widget = forms.DateInput(format='%m/%d/%Y'),
            input_formats=('%m/%d/%Y',)
        )


    def __init__(self, *args, **kwargs):
        super(FotoForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):

            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

            #if field == 'fecha':
                #self.fields['fecha'].widget.attrs[format]=('%m/%d/%Y')

            if field == 'cliente':
                self.fields['cliente'].widget.attrs['readonly']=True

clientes/views.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.urls import reverse
from django.shortcuts import render
import os
from django.conf import settings
from .forms import ClienteForm, DocuForm, FotoForm
from .models import Cliente, Documentos, Fotos



class ListadoClientes(ListView):
    model = Cliente
    template_name = 'listado_clientes.html'
    context_object_name ='clientes'

class DetalleCliente(DetailView):
    model = Cliente
    template_name = 'detalle_cliente.html'

class ModificarCliente(UpdateView):
    model = Cliente
    template_name = 'modificar_cliente.html'
    form_class = ClienteForm
    success_url = reverse_lazy('clientes:listado_clientes')

class NuevoCliente(CreateView):
    model = Cliente
    template_name = 'nuevo_cliente.html'
    form_class = ClienteForm
    success_url = reverse_lazy('clientes:listado_clientes')

class EliminarCliente(DeleteView):
    model = Cliente
    template_name = 'cliente_eliminar.html'
    success_url = reverse_lazy('clientes:listado_clientes')






def documentos_cliente(request,pk):
    ext = [".jpg", ".png", "gif", ",jpeg"]
    file_path = os.path.join(settings.DJANGO_ROOT)
    print(file_path)
    print("_" * 50)
    docus = Documentos.objects.filter(cliente_id=pk)
    return render(request, 'documentos.html', context={'docs': docus, 'img_extension': ext, 'path':file_path, 'pk': pk})


class DocumentosNuevo(CreateView):
    model = Documentos
    template_name = 'formulario_docu.html'
    form_class = DocuForm
    client = None
    success_url= None


    def get_object(self, queryset=None):
        return queryset.get(int(client=self.client))

    def form_valid(self, form):
        qsClient = Cliente.objects.get(id=self.kwargs['client'])
        form.instance.cliente = qsClient
        DocumentosNuevo.success_url = reverse('clientes:documentos_cliente', kwargs={'pk': self.kwargs['client']})

        return super(DocumentosNuevo, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        context=locals()
        context['client']=self.kwargs['client']
        context['form'] =self.form_class

        return render(request, 'formulario_docu.html', context)


class EliminarDocumento(DeleteView):
    model = Documentos
    template_name = 'doc_confirm_delete.html'
    client = None
    success_url = None

    def delete(self, request, *args, **kwargs):
        print("."*50)
        print (self.kwargs['pk'])
        qsDocumentos = Documentos.objects.get(id=self.kwargs['pk'])
        EliminarDocumento.success_url = reverse_lazy('clientes:documentos_cliente', kwargs={'pk': qsDocumentos.cliente_id})
        return super(EliminarDocumento, self).delete(request, *args, **kwargs)


class ModificarDocumento(UpdateView):
    model = Documentos
    template_name = 'formulario_doc_editar.html'
    form_class = DocuForm
    client = None
    success_url= None

    def form_valid(self, form):
        qsDocumentos = Documentos.objects.get(id=self.kwargs['pk'])
        qsClient = Cliente.objects.get(id = qsDocumentos.cliente_id)
        form.instance.cliente = qsClient
        ModificarDocumento.success_url = reverse('clientes:documentos_cliente', kwargs={'pk': qsDocumentos.cliente_id})
        return super(ModificarDocumento, self).form_valid(form)





def fotos_cliente(request,pk):
    ext = [".jpg", ".png", "gif", ",jpeg"]
    file_path = os.path.join(settings.DJANGO_ROOT)
    print(file_path)
    print("_" * 50)
    fotos = Fotos.objects.filter(cliente_id=pk)
    return render(request, 'fotos.html', context={'fotos': fotos, 'img_extension': ext, 'path':file_path, 'pk': pk})


class FotoNueva(CreateView):
    model = Fotos
    template_name = 'formulario_foto.html'
    form_class = FotoForm
    client = None
    success_url= None


    def get_object(self, queryset=None):
        return queryset.get(int(client=self.client))

    def form_valid(self, form):
        qsClient = Cliente.objects.get(id=self.kwargs['client'])
        form.instance.cliente = qsClient
        FotoNueva.success_url = reverse('clientes:fotos_cliente', kwargs={'pk': self.kwargs['client']})

        return super(FotoNueva, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        context=locals()
        context['client']=self.kwargs['client']
        context['form'] =self.form_class

        return render(request, 'formulario_foto.html', context)


class EliminarFoto(DeleteView):
    model = Fotos
    template_name = 'foto_confirm_delete.html'
    client = None
    success_url = None

    def delete(self, request, *args, **kwargs):
        print("."*50)
        print (self.kwargs['pk'])
        qsFotos = Fotos.objects.get(id=self.kwargs['pk'])
        EliminarFoto.success_url = reverse_lazy('clientes:fotos_cliente', kwargs={'pk': qsFotos.cliente_id})
        return super(EliminarFoto, self).delete(request, *args, **kwargs)


class ModificarFoto(UpdateView):
    model = Fotos
    template_name = 'formulario_foto_editar.html'
    form_class = FotoForm
    client = None

    def form_valid(self, form):
        qsFotos = Fotos.objects.get(id=self.kwargs['pk'])
        qsClient = Cliente.objects.get(id = qsFotos.cliente_id)
        form.instance.cliente = qsClient
        ModificarFoto.success_url = reverse_lazy('clientes:fotos_cliente', kwargs={'pk': qsFotos.cliente_id})
        return super(ModificarFoto, self).form_valid(form)

clientes/templates/cliente_eliminar.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

  <h5> Eliminando Cliente id:{{ object.pk }}</h5>

            <form method="post" action="{% url 'clientes:cliente_eliminar' object.pk %}">{% csrf_token %}
                <p>Seguro que quieres eliminar este cliente?</p>
                <input type="submit" class="btn btn-danger" value="Eliminar">
            </form>


</div>
    </div>
  </div>
</div>

{% endblock cuerpo %}

clientes/templates/doc_confirm_delete.html
{% load staticfiles %}
{% block cuerpo %}


<div class="container">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

            <h5> Eliminando Factura "{{ object }}" </h5>

            <form method="post" action="{% url 'clientes:documento_eliminar' object.pk %}">{% csrf_token %}
                <p>Seguro que quieres eliminar esta factura?</p>
                <input type="submit" class="btn btn-danger" value="Eliminar">
            </form>
      </div>
    </div>
  </div>
</div>

{% endblock cuerpo %}

clientes/templates/documentos.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}
{% with menudocumento="1" pk=pk %}
	{% include "menucliente.html" %}
{% endwith %}
<br>

<div class="row">
	<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card ">
		<div class="card">
			<div class="card-body">

				<a onclick="return abrir_modal('{% url 'clientes:documentos_nuevo' client=pk %}')">
	  				<span class="btn btn-info btn-sm">Agregar Factura</span>
				</a>

				<h3 class="card-title"></h3>


				{% if docs %}
					<div class="row">
						<div class="col"><p>Tipo</p></div>
						<div class="col"><p>Fecha</p></div>
						<div class="col"><p></p></div>

					</div>
					<hr>


					{% for 	doc in docs %}
					<div class="row">
						<div class="col-sm-3 col-md-3 col-lg-3"><p>{{ doc.tipodocumento }}</p></div>
						<div class="col-sm-3 col-md-3 col-lg-3 "><p>{{ doc.fecha_documento }}</p></div>
						<div class="col-sm-3 col-md-3 col-lg-5"><p>
							<a class="btn btn-outline-primary btn-sm"
										   data-toggle="collapse"
										   href="#doc{{ doc.id }}"
										   role="button"
										   aria-expanded="false"
										   aria-controls="doc{{ doc.id }}">ver
							</a>
							<a onclick="return abrir_modal('{% url 'clientes:documento_modificar' doc.pk%}')">
								<span class="btn btn-outline-info btn-sm">edit</span>
							</a>
							<a onclick="return abrir_modal('{% url 'clientes:documento_eliminar' doc.pk%}')">
								<span class="btn btn-outline-danger btn-sm mdi mdi-delete"></span>
							</a>
						</p>
						</div>
						</div>
			        {% endfor %}

				{% else %}
					No tiene Documentos
				{% endif %}

				<hr>

			</div>
		</div>
	</div>



<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card " id="myGroup">

				  {% for doc in docs %}
							  <div class="collapse" id="doc{{ doc.id }}" data-parent="#myGroup">
									 {{ doc.etiqueta  }} <hr>
								  <div class="card card-body">

										{% if not doc.documento %}
											<img class="container" src="{%  static 'assets/images/not_found.png' %}" ></a>
										{% else %}
									  		<img class="container" src="{{ doc.documento.url }}" ></a>
									  {% endif %}
								  </div>
							  </div>
				  {% endfor %}

</div>


</div> <!--  end row -->


<div id="popup" class="modal fade" role="dialog">  </div>


{% endblock cuerpo %}

{% block js %}


<script>
function abrir_modal(url)
{
	$('#popup').load(url, function()
	{
		$(this).modal('show');
	});
	return false;
}

function cerrar_modal()
{
	$('#popup').modal('hide');
	return false;
}




</script>

<!--  custom js for this page-->
<script src="{% static 'assets/js/shared/modal-demo.js' %}"></script>

{% endblock js %}

clientes/templates/fotos.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}
{% with menufotos="1" pk=pk %}
	{% include "menucliente.html" %}
{% endwith %}
<br>

<div class="row">

	<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card ">
		<div class="card">
			<div class="card-body">

				<a onclick="return abrir_modal('{% url 'clientes:foto_nueva' client=pk %}')">
	  				<span class="btn btn-info btn-sm">Agregar foto</span>
				</a>

				<h3 class="card-title"></h3>

				{% if fotos %}

					<div class="row">
						<div class="col"><p>Etiqueta</p></div>
						<div class="col"><p>Fecha</p></div>
						<div class="col"><p></p></div>
					</div>
					<hr>

                    {% for 	foto in fotos %}

						<div class="row">
							<div class="col-sm-3 col-md-3 col-lg-3"><p>{{ foto.etiqueta | truncatechars:17 }}</p></div>
							<div class="col-sm-3 col-md-3 col-lg-3"><p>{{ foto.fecha_foto }}</p></div>
							<div class="col-sm-3 col-md-3 col-lg-5">
								<a class="btn btn-outline-primary btn-sm"
										   data-toggle="collapse"
										   href="#foto{{ foto.id }}"
										   role="button"
										   aria-expanded="false"
										   aria-controls="foto{{ foto.id }}">ver
								</a>
								<a onclick="return abrir_modal('{% url 'clientes:foto_modificar' foto.pk%}')">
								<span class="btn btn-outline-info btn-sm">edit</span>
								</a>
								<a onclick="return abrir_modal('{% url 'clientes:foto_eliminar' foto.pk%}')">
									<span class="btn btn-outline-danger btn-sm mdi mdi-delete"></span>
								</a>
							</div>
						</div>
			        {% endfor %}

				{% else %}
					No tiene imagenes
				{% endif %}

				<hr>

			</div>
		</div>
	</div>




<div class="col-sm-6 col-md-6 col-lg-6 grid-margin stretch-card " id="myGroup">

				  {% for 	foto in fotos %}
							  <div class="collapse" id="foto{{ foto.id }}" data-parent="#myGroup">
									 {{ foto.etiqueta  }} <hr>
								  <div class="card card-body">
								   <!--<div class="preview-image">-->
										{% if not foto.foto %}
											<img class="container" src="{%  static 'assets/images/not_found.png' %}" ></a>
										{% else %}
									  <img class="container" src="{{ foto.foto.url }}" ></a>
									  {% endif %}
									  <!--</div>-->
								  </div>
							  </div>
				  {% endfor %}

</div>


</div> <!--  end row -->







<div id="popup" class="modal fade" role="dialog">  </div>





{% endblock cuerpo %}

{% block js %}


<script>
function abrir_modal(url)
{
	$('#popup').load(url, function()
	{
		$(this).modal('show');
	});
	return false;
}

function cerrar_modal()
{
	$('#popup').modal('hide');
	return false;
}




</script>

<!--  custom js for this page-->
<script src="{% static 'assets/js/shared/modal-demo.js' %}"></script>

{% endblock js %}

clientes/templates/listado_clientes.html
{% extends "base.html" %}
{% load staticfiles %}
{% block cuerpo %}

      <!-- partial -->

<style>
.dataTables_wrapper .dataTable .btn{
     padding: 0.4rem 0.9rem!important;
    vertical-align: top;
}
</style>


<div class="row">
  <div class="col-md-12">
            <div class="card" >
              <div class="card-body">
                  <h3 class="card-title">Listado de Clientes</h3>
                  <p class="card-description">  </p>
                <div class="row">
                  <div class="col-12 table-responsive">
                    <table id="tabla" class="table">
                      <thead>
                        <tr>
                             <th>Nombre Completo</th>
                             <th>DNI </th>
                             <th>Fecha Nacimiento</th>
                             <th>Teléfono</th>
                             <th> <a role="button" class="btn btn-outline-warning btn-sm" href="{% url 'clientes:nuevo_cliente' %}">Nuevo Cliente</a></th>
                        </tr>
                      </thead>

                      <tbody>

                        {% for 	client in clientes %}

                            <tr>

                                <td>{{ client.nombre | default_if_none:"" | truncatechars:25 }}&nbsp;{{ client.apellidos | default_if_none:"" | truncatechars:25 }}</td>
                                <td>{{ client.num_documento | default_if_none:"" | truncatechars:25 }}</td>
                                <td>{{ client.fecha_nacimiento | default_if_none:"" }}</td>
                                <td>{{ client.movil | default_if_none:"" }} </td>
                                <td>
                                    <a role="button" class="btn btn-outline-primary btn-sm" href="{% url 'clientes:detalle_cliente' client.pk %}">ver</a>

                                    <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'clientes:modificar_cliente' client.pk %}">editar</a>


                                    <a onclick="return abrir_modal('{% url 'clientes:cliente_eliminar' client.pk %}')">
                                        <span class="btn btn-outline-danger mdi mdi-delete"></span></a>
                                </td>
                            </tr>
			            {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
  </div>
</div>
<div id="popup" class="modal fade" role="dialog">


</div>
{% endblock cuerpo %}

{% block js %}

<script>
function abrir_modal(url)
{
	$('#popup').load(url, function()
	{
		$(this).modal('show');
	});
	return false;
}

function cerrar_modal()
{
	$('#popup').modal('hide');
	return false;
}

$(document).ready(function()
{
    var table = $('#tabla').dataTable( {
        "language": {
        	url: "/static/assets/localizacion/es_ES.json"
        }
    } );
});
</script>


    <!-- Custom js for this page
    <script src="{% static '/assets/js/shared/data-table.js' %}"></script>-->
          <script src="{% static 'assets/js/shared/modal-demo.js' %}"></script>
   <!--<script src="{% static 'assets/js/shared/jquery.dataTables.min.js' %}"></script>-->
   <!-- End custom js for this page-->

{% endblock js %}